const errorCodes = {
  MASTER_DATA: {
    EXIST_BUSINESS_UNIT_TYPE_NAME: 2718,
    EXIST_OFFICE_NAME: 1906,
    EXIST_OFFICE_TYPE_NAME: 2729
  },
  WORK: {
    EXIST_CATEGORY_NAME: 460,
    EXIST_GROUP_NAME: 2909,
    EXIST_REQUEST_PORTAL_NAME: 2918,
    EXIST_CATEGORY_NAME_EN: 2931,
    EXIST_CATEGORY_NAME_VI: 2932,
    EXIST_REFERENCE_CATEGORY: 2930,
    EXIST_REFERENCE_REQUEST_GROUP: 2925,
    EXIST_REFERENCE_REQUEST_PORTAL: 2929
  },
  WORKPLACE: {
    SERVICE: {
      SERVICE_ALREADY_EXIST: "S805",
      SERVICE_NOT_EXIST: "S806",
      SERVICE_HAS_BEEN_USED: "S808",
      ADD_OWNER_NOT_EXIST: "O806",
      UPDATE_ALL_OWNER_NOT_EXIST: "O806",
      UPDATE_CONTAIN_OWNER_NOT_EXIST: "O807",
      ADD_CONFIG_ERROR: "CFG807",
      ACTION_HAS_BEEN_USED: "A808"
    },
    LOCATION_TYPE: {
      LOCATION_TYPE_ALREADY_EXIST: "T805",
      LOCATION_TYPE_NOT_EXIST: "T806",
      LOCATION_TYPE_HAS_BEEN_USED: "T808"
    },
    LOCATION: {
      LOCATION_ALREADY_EXIST: "L805",
      LOCATION_NOT_EXIST: "L806",
      LOCATION_HAS_BEEN_USED: "L808",
      ADD_OWNER_NOT_EXIST: "O806",
      UPDATE_ALL_OWNER_NOT_EXIST: "O806",
      UPDATE_CONTAIN_OWNER_NOT_EXIST: "O807"
    },
    DEVICE: {
      DEVICE_ALREADY_EXIST: "DV805",
      DEVICE_NOT_EXIST: "DV806",
      ADD_CONFIG_ERROR: "CFG807"
    },
    SOURCE: {
      SOURCE_ALREADY_EXIST: "SRC805",
      SOURCE_NOT_EXIST: "SRC806",
      IMPORT_DATA_FAIL: "SRC808",
      USERS_EXIST: "US806"
    },
    ROLE: {
      ROLE_ALREADY_EXIST: "ROLE805",
      ROLE_NOT_EXIST: "ROLE806",
      DELETE_ALL_USERS: "ROLE807",
      PERMISSION_DENIED: "PER808"
    },
    SECRET_KEY: {
      SECRET_KEY_ALREADY_EXIST: "SEC805",
      SECRET_KEY_NOT_EXIST: "SEC806"
    }
  }
};

export default errorCodes;
